# Site settings
title: Jekyll Theme - Lazy
email: pirocorp@abv.bg
description: >- # this means to ignore newlines until "baseurl:"
  It's minimal and lazy!
baseurl: "/project" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

destination: "docs"

twitter_username: pirocorp
github_username:  pirocorp

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - scss
  - gulpfile.js
  - package.json
  - package-lock.json
  - .vscode